server:
  port: 8085
spring:
  application:
  name: spring-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/peter5645/config/
          search-paths: testConfig
          username:
          password: